// <auto-generated />
using System;
using LecturasApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LecturasApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250709235545_FixClienteIdType")]
    partial class FixClienteIdType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("LecturasApi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("LecturasApi.Models.Lectura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("MedidorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MedidorId");

                    b.ToTable("Lecturas");
                });

            modelBuilder.Entity("LecturasApi.Models.Medidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Medidores");
                });

            modelBuilder.Entity("LecturasApi.Models.Lectura", b =>
                {
                    b.HasOne("LecturasApi.Models.Medidor", "Medidor")
                        .WithMany("Lecturas")
                        .HasForeignKey("MedidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medidor");
                });

            modelBuilder.Entity("LecturasApi.Models.Medidor", b =>
                {
                    b.HasOne("LecturasApi.Models.Cliente", "Cliente")
                        .WithMany("Medidor")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("LecturasApi.Models.Cliente", b =>
                {
                    b.Navigation("Medidor");
                });

            modelBuilder.Entity("LecturasApi.Models.Medidor", b =>
                {
                    b.Navigation("Lecturas");
                });
#pragma warning restore 612, 618
        }
    }
}
